// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Dobrev IT Ltd
//
// This file is part of RetiMesh Node.
//
// RetiMesh Node is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// RetiMesh Node is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with RetiMesh Node. If not, see <https://www.gnu.org/licenses/>.


// ============================================================================
//  OtaVerify.h — the signature check FirmwareManifest asks for
//
//  FirmwareManifest.h takes the verifier as a function pointer so its policy
//  can be tested without crypto. This is the one the firmware passes, and the
//  one the tests pass when they check a manifest the signing tool really
//  signed: two callers, one function, so nothing can verify an update by a
//  route that no test ever runs.
//
//  Ed25519 comes from the same library microReticulum uses, so a node carries
//  one implementation rather than two.
// ============================================================================
#pragma once

#include <stddef.h>
#include <stdint.h>

#include <Ed25519.h>

#include "FirmwareManifest.h"
#include "OtaRoots.h"

namespace Ota {

// Matches FirmwareManifest::Verifier. Ed25519::verify is total: any 64 bytes
// are a well-formed input, and a signature that is not one simply fails, so
// there is nothing to validate before calling it.
inline bool verifySignature(const uint8_t* sig, const uint8_t* key,
                            const uint8_t* msg, size_t len) {
  return Ed25519::verify(sig, key, msg, len);
}

// The compiled-in trust anchors, in the shape Policy wants. OtaRoots.h is
// generated by tools/fw_sign.py from the public halves; the private halves are
// not on this machine, in this repository, or in CI.
inline const uint8_t (*roots())[FirmwareManifest::KEY_SIZE] {
  static_assert(sizeof(OTA_ROOT_KEYS[0]) == FirmwareManifest::KEY_SIZE,
                "a root key is not the size the manifest format expects");
  return OTA_ROOT_KEYS;
}

inline size_t rootCount() { return OTA_ROOT_COUNT; }

}  // namespace Ota
